/*
 * Token Tracker Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StripeEventData
 */
public class StripeEventDataTest {
    private final StripeEventData model = new StripeEventData();

    /**
     * Model tests for StripeEventData
     */
    @Test
    public void testStripeEventData() {
        // TODO: test StripeEventData
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'previousAttributes'
     */
    @Test
    public void previousAttributesTest() {
        // TODO: test previousAttributes
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

}
