/*
 * Token Tracker Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Tokentracker.JSON;

/**
 * TokentrackerAdjustTokenBalanceResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-14T09:02:19.138901619Z[Etc/UTC]")
public class TokentrackerAdjustTokenBalanceResponse {
  public static final String SERIALIZED_NAME_NEW_BALANCE = "newBalance";
  @SerializedName(SERIALIZED_NAME_NEW_BALANCE)
  private String newBalance;

  public TokentrackerAdjustTokenBalanceResponse() {
  }

  public TokentrackerAdjustTokenBalanceResponse newBalance(String newBalance) {
    this.newBalance = newBalance;
    return this;
  }

   /**
   * Get newBalance
   * @return newBalance
  **/
  @javax.annotation.Nullable
  public String getNewBalance() {
    return newBalance;
  }

  public void setNewBalance(String newBalance) {
    this.newBalance = newBalance;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokentrackerAdjustTokenBalanceResponse tokentrackerAdjustTokenBalanceResponse = (TokentrackerAdjustTokenBalanceResponse) o;
    return Objects.equals(this.newBalance, tokentrackerAdjustTokenBalanceResponse.newBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newBalance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokentrackerAdjustTokenBalanceResponse {\n");
    sb.append("    newBalance: ").append(toIndentedString(newBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("newBalance");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TokentrackerAdjustTokenBalanceResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TokentrackerAdjustTokenBalanceResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TokentrackerAdjustTokenBalanceResponse is not found in the empty JSON string", TokentrackerAdjustTokenBalanceResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TokentrackerAdjustTokenBalanceResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TokentrackerAdjustTokenBalanceResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("newBalance") != null && !jsonObj.get("newBalance").isJsonNull()) && !jsonObj.get("newBalance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `newBalance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("newBalance").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TokentrackerAdjustTokenBalanceResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TokentrackerAdjustTokenBalanceResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TokentrackerAdjustTokenBalanceResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TokentrackerAdjustTokenBalanceResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TokentrackerAdjustTokenBalanceResponse>() {
           @Override
           public void write(JsonWriter out, TokentrackerAdjustTokenBalanceResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TokentrackerAdjustTokenBalanceResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TokentrackerAdjustTokenBalanceResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TokentrackerAdjustTokenBalanceResponse
  * @throws IOException if the JSON string is invalid with respect to TokentrackerAdjustTokenBalanceResponse
  */
  public static TokentrackerAdjustTokenBalanceResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TokentrackerAdjustTokenBalanceResponse.class);
  }

 /**
  * Convert an instance of TokentrackerAdjustTokenBalanceResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

